version: '3.8'

services:
  tests:
    build: .
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      - PYTHONPATH=/app

  allure:
    image: frankescobar/allure-docker-service
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=5
      - KEEP_HISTORY=1
    volumes:
      - ./allure-results:/app/allure-results
    ports:
      - "5050:5050"
    depends_on:
      - tests
